### ISSUE TITLE
Nonce replay attack protection

### ISSUE THREAD

**Issue by Erwane** [jasny/http-signature#1]
Hi,

Do you plan to add the nonce token in signature ?

https://web-payments.org/specs/source/http-signature-nonces/

nonce is not included in hmac signature but passed in "Signature" header, and checked by the API

Thanks

**Comment by jasny** [comment]
Ok

**Comment by jasny** [comment]
@Erwane Even though I started on this (see the ['nonce'](https://github.com/jasny/http-signature/tree/nonce) branch), I'm not going to include it.

I understand why it's useful to add a nonce to prevent replay attacks, but the way as described in these specs don't seem right.

From reading the specs it's clear that the author wants to a fingerprint + the nonce to be unique. For this fingerprint, it uses a new field `clientId`, where it would otherwise use an IP.

However, the thing that should be stored to identify a unique request is the signature. A nonce is only used to create a unique message for the signature, and thus a unique signature, even if all other parameters are the same. Adding a `clientId` is completely unnecessary.

I don't believe there is much support for this addition to the standard, as other libs also don't include it. As an alternative method, replay attacks could be accomplished by adding an `X-Nonce` header.

Feel free to run a fork of this lib, with this feature included starting from the 'nonce' branch.

**Comment by Erwane** [comment]
Thanks, i used an `nonce` header and add "nonce" in headers list for signature.

Even if replay attack is importante, i think you're right and should not be managed by http-signature.
